# Generated by Django 6.0.5 on 2026-05-20 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_alter_transaction_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='source',
            field=models.CharField(choices=[('manual', 'Ручной'), ('bank_tinkoff', 'Тинькофф')], default='manual', max_length=20),
        ),
    ]
