# Generated by Django 6.0.5 on 2026-05-20 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_transaction_external_id_transaction_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='ID транзакции в банке'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='source',
            field=models.CharField(choices=[('manual', 'Ручной ввод'), ('bank_tinkoff', 'Тинькофф'), ('bank_sber', 'Сбер')], default='manual', max_length=20, verbose_name='Источник'),
        ),
    ]
