# Generated by Django 6.0.5 on 2026-05-20 19:38

import django.db.models.deletion
import encrypted_fields.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(choices=[('tinkoff', 'Тинькофф'), ('sber', 'Сбер')], max_length=20)),
                ('access_token', encrypted_fields.fields.EncryptedTextField()),
                ('refresh_token', encrypted_fields.fields.EncryptedTextField()),
                ('token_expires_at', models.DateTimeField()),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'bank_name')},
            },
        ),
        migrations.CreateModel(
            name='Synclog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('transactions_found', models.IntegerField(default=0)),
                ('transactions_created', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integrations.bankconnection')),
            ],
        ),
    ]
